INSERT INTO `v9_category` VALUES('14','1','content','0','11','9','0,51,9','0','14','中国人民大学','','','','Home/anxuexiaofenlei/','zhongguorenmindaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=14','16777213','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','14','1','0','zhongguorenmindaxue','');
INSERT INTO `v9_category` VALUES('13','1','content','0','11','9','0,51,9','0','13','清华大学','','','','Home/anxuexiaofenlei/','qinghuadaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=13','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','13','1','0','qinghuadaxue','');
INSERT INTO `v9_category` VALUES('11','1','content','0','11','51','0,51','1','11,43,44,45,46,47,48,49','按机构分类','','','','Home/','anjigoufenlei','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=11','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','11','1','0','anjigoufenlei','');
INSERT INTO `v9_category` VALUES('10','1','content','0','11','51','0,51','1','10,31,32,33,34,35,36,37,38,39,40,41,42','按学科分类','','','','Home/','anxuekefenlei','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=10','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','10','1','0','anxuekefenlei','');
INSERT INTO `v9_category` VALUES('9','1','content','0','11','51','0,51','1','9,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30,54','按学校分类','','','','Home/','anxuexiaofenlei','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=9','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','9','1','0','anxuexiaofenlei','');
INSERT INTO `v9_category` VALUES('15','1','content','0','11','9','0,51,9','0','15','北京师范大学','','','','Home/anxuexiaofenlei/','beijingshifandaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=15','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','15','1','0','beijingshifandaxue','');
INSERT INTO `v9_category` VALUES('16','1','content','0','11','9','0,51,9','0','16','南开大学','','','','Home/anxuexiaofenlei/','nankaidaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=16','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','16','1','0','nankaidaxue','');
INSERT INTO `v9_category` VALUES('17','1','content','0','11','9','0,51,9','0','17','北京大学','','','','Home/anxuexiaofenlei/','beijingdaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=17','16777213','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','17','1','0','beijingdaxue','');
INSERT INTO `v9_category` VALUES('18','1','content','0','11','9','0,51,9','0','18','耶鲁','','','','Home/anxuexiaofenlei/','yelu','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=18','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','18','1','0','yelu','');
INSERT INTO `v9_category` VALUES('19','1','content','0','11','9','0,51,9','0','19','哈佛','','','','Home/anxuexiaofenlei/','hafo','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=19','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','19','1','0','hafo','');
INSERT INTO `v9_category` VALUES('20','1','content','0','11','9','0,51,9','0','20','斯坦福','','','','Home/anxuexiaofenlei/','sitanfu','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=20','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','20','1','0','sitanfu','');
INSERT INTO `v9_category` VALUES('21','1','content','0','11','9','0,51,9','0','21','牛津','','','','Home/anxuexiaofenlei/','niujin','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=21','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','21','1','0','niujin','');
INSERT INTO `v9_category` VALUES('22','1','content','0','11','9','0,51,9','0','22','哥伦比亚','','','','Home/anxuexiaofenlei/','gelunbiya','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=22','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','22','1','0','gelunbiya','');
INSERT INTO `v9_category` VALUES('23','1','content','0','11','9','0,51,9','0','23','麻省','','','','Home/anxuexiaofenlei/','masheng','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=23','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','23','1','0','masheng','');
INSERT INTO `v9_category` VALUES('24','1','content','0','11','9','0,51,9','0','24','普林斯顿','','','','Home/anxuexiaofenlei/','pulinsidun','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=24','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','24','1','0','pulinsidun','');
INSERT INTO `v9_category` VALUES('25','1','content','0','11','9','0,51,9','0','25','伯克利','','','','Home/anxuexiaofenlei/','bokeli','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=25','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','25','1','0','bokeli','');
INSERT INTO `v9_category` VALUES('26','1','content','0','11','9','0,51,9','0','26','复旦','','','','Home/anxuexiaofenlei/','fudan','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=26','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','26','1','0','fudan','');
INSERT INTO `v9_category` VALUES('27','1','content','0','11','9','0,51,9','0','27','中国地质大学','','','','Home/anxuexiaofenlei/','zhongguodizhidaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=27','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','27','1','0','zhongguodizhidaxue','');
INSERT INTO `v9_category` VALUES('28','1','content','0','11','9','0,51,9','0','28','北京邮电大学','','','','Home/anxuexiaofenlei/','beijingyoudiandaxue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=28','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','28','1','0','beijingyoudiandaxue','');
INSERT INTO `v9_category` VALUES('30','1','content','0','11','9','0,51,9','0','30','加州艺术学院','','','','Home/anxuexiaofenlei/','jiazhouyishuxueyuan','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=30','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','30','1','0','jiazhouyishuxueyuan','');
INSERT INTO `v9_category` VALUES('31','1','content','0','11','10','0,51,10','0','31','经济','','','','Home/anxuekefenlei/','jingji','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=31','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','31','1','0','jingji','');
INSERT INTO `v9_category` VALUES('32','1','content','0','11','10','0,51,10','0','32','人文','','','','Home/anxuekefenlei/','renwen','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=32','16777203','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','32','1','0','renwen','');
INSERT INTO `v9_category` VALUES('33','1','content','0','11','10','0,51,10','0','33','理科','','','','Home/anxuekefenlei/','like','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=33','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','33','1','0','like','');
INSERT INTO `v9_category` VALUES('34','1','content','0','11','10','0,51,10','0','34','哲学','','','','Home/anxuekefenlei/','zhexue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=34','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','34','1','0','zhexue','');
INSERT INTO `v9_category` VALUES('35','1','content','0','11','10','0,51,10','0','35','工科','','','','Home/anxuekefenlei/','gongke','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=35','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','35','1','0','gongke','');
INSERT INTO `v9_category` VALUES('36','1','content','0','11','10','0,51,10','0','36','其他科学','','','','Home/anxuekefenlei/','qitakexue','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=36','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','36','1','0','qitakexue','');
INSERT INTO `v9_category` VALUES('37','1','content','0','11','10','0,51,10','0','37','历史','','','','Home/anxuekefenlei/','lishi','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=37','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','37','1','0','lishi','');
INSERT INTO `v9_category` VALUES('38','1','content','0','11','10','0,51,10','0','38','社会','','','','Home/anxuekefenlei/','shehui','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=38','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','38','1','0','shehui','');
INSERT INTO `v9_category` VALUES('39','1','content','0','11','10','0,51,10','0','39','TED','','','','Home/anxuekefenlei/','ted','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=39','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','39','1','0','ted','');
INSERT INTO `v9_category` VALUES('40','1','content','0','11','10','0,51,10','0','40','讲座','','','','Home/anxuekefenlei/','jiangzuo','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=40','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','40','1','0','jiangzuo','');
INSERT INTO `v9_category` VALUES('41','1','content','0','11','10','0,51,10','0','41','中国大学公开课','','','','Home/anxuekefenlei/','zhongguodaxuegongkaike','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=41','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','41','1','0','zhongguodaxuegongkaike','');
INSERT INTO `v9_category` VALUES('42','1','content','0','11','10','0,51,10','0','42','时尚','','','','Home/anxuekefenlei/','shishang','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=42','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','42','1','0','shishang','');
INSERT INTO `v9_category` VALUES('43','1','content','0','11','11','0,51,11','0','43','新浪教育盛典','','','','Home/anjigoufenlei/','xinlangjiaoyushengdian','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=43','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','43','1','0','xinlangjiaoyushengdian','');
INSERT INTO `v9_category` VALUES('44','1','content','0','11','11','0,51,11','0','44','影视工业网','','','','Home/anjigoufenlei/','yingshigongyewang','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=44','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','44','1','0','yingshigongyewang','');
INSERT INTO `v9_category` VALUES('45','1','content','0','11','11','0,51,11','0','45','《开讲啦》','','','','Home/anjigoufenlei/','kaijiangla','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=45','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','45','1','0','kaijiangla','');
INSERT INTO `v9_category` VALUES('46','1','content','0','11','11','0,51,11','0','46','可汗学院','','','','Home/anjigoufenlei/','kehanxueyuan','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=46','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','46','1','0','kehanxueyuan','');
INSERT INTO `v9_category` VALUES('47','1','content','0','11','11','0,51,11','0','47','TED','','','','Home/anjigoufenlei/','ted','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=47','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','47','1','0','ted','');
INSERT INTO `v9_category` VALUES('48','1','content','0','11','11','0,51,11','0','48','时尚100','','','','Home/anjigoufenlei/','shishang100','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=48','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','48','1','0','shishang100','');
INSERT INTO `v9_category` VALUES('49','1','content','0','11','11','0,51,11','0','49','锡恩MIP云管理学院','','','','Home/anjigoufenlei/','xienmipyunguanlixueyuan','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=49','16777214','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','49','1','0','xienmipyunguanlixueyuan','');
INSERT INTO `v9_category` VALUES('50','1','content','0','11','51','0,51','0','50','公开课-珍藏版','','','','Home/','pulic','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=50','16777215','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','50','1','0','gongkaike-zhencangban','');
INSERT INTO `v9_category` VALUES('51','1','content','0','11','0','0','1','51,9,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30,54,10,31,32,33,34,35,36,37,38,39,40,41,42,11,43,44,45,46,47,48,49,50','首页导航','','','','','Home','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=51','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','51','1','0','shouyedaohang','');
INSERT INTO `v9_category` VALUES('54','1','content','0','11','9','0,51,9','0','54','台湾大学','','','','Home/anxuexiaofenlei/','twdx','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=54','0','0','array (
  \'workflowid\' => \'\',
  \'ishtml\' => \'0\',
  \'content_ishtml\' => \'0\',
  \'create_to_html_root\' => \'0\',
  \'template_list\' => \'sina\',
  \'category_template\' => \'category\',
  \'list_template\' => \'list_sina\',
  \'show_template\' => \'show\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'presentpoint\' => \'1\',
  \'defaultchargepoint\' => \'0\',
  \'paytype\' => \'0\',
  \'repeatchargedays\' => \'1\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'16\',
)','54','1','0','taiwandaxue','');
INSERT INTO `v9_category` VALUES('53','1','content','1','0','0','0','0','53','页底信息','','','','','footer','http://bordon.xicp.net:9999/phpcms/index.php?m=content&c=index&a=lists&catid=53','0','0','array (
  \'ishtml\' => \'0\',
  \'template_list\' => \'sina\',
  \'page_template\' => \'page\',
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
  \'category_ruleid\' => \'6\',
  \'show_ruleid\' => \'\',
  \'repeatchargedays\' => \'1\',
)','53','1','0','yedixinxi','');
