<?php
return array (
  476 => 
  array (
    'id' => '476',
    'catid' => '64',
    'typeid' => '0',
    'title' => 'asdfasfd',
    'style' => '',
    'thumb' => 'http://bordon.xicp.net:8888/phpcms/uploadfile/thumb/5399b63d6e266.jpg',
    'keywords' => '',
    'description' => '',
    'posids' => '0',
    'url' => 'http://bordon.xicp.net:8888/phpcms/index.php?m=content&c=index&a=show&catid=64&id=476',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'doraprince',
    'inputtime' => '1402582589',
    'updatetime' => '1402582589',
    'vision' => '',
    'video_category' => '',
    'tea_des' => '',
    'tea' => '',
    'tea_name' => '',
    'hitsid' => 'c-11-476',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>